### ISSUE TITLE
2D & 3D Lidar see through from vehicle

### ISSUE THREAD

**Issue by Hisham178** [rapyuta-robotics/turtlebot3-UE#73]
I noticed I can see 2d and 3d lidar where logically I should not. Is there any config to make it  disappears? 
![Screenshot from 2023-08-10 14-38-26]

(https://github.com/rapyuta-robotics/turtlebot3-UE/assets/110361659/814b67af-2912-48af-9705-31e098d50ee7)

**Comment by yuokamoto** [comment]
I can make it work somehow by tuning DepthIntensity parameter
https://docs.unrealengine.com/4.27/en-US/API/Runtime/Engine/Components/ULineBatchComponent/DrawPoint/

Since I can't find documentation, I'm not sure this is proper solution but created PR.
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/pull/196
