### ISSUE TITLE
[question] What do all the setup scripts do?

### ISSUE THREAD

**Issue by alexzhang13** [rapyuta-robotics/turtlebot3-UE#74]
Is it possible to just use the plugins without all of the extra setup that is written in the README? Just looking through, I don't fully understand what the setup and build scripts do that are required to get this project to work.

I'm also curious if it's possible to get everything to work on the Unreal side without specific ROS dependencies like nav2. I'm looking to have basically Unreal with the ROS bridge running on a server, and then the client would be running stuff like nav2 or teleop control to communicate information to the robots in Unreal through specified topics.

**Comment by yuokamoto** [comment]
- run_editor.sh does pass parameter, start ros2 discovery server, then start editor. you can run project without script then project use default param and ros2 dds server and fastdds_setup needs to be done separately
- make_editor.sh just build editor. you ca nbuild edtor without the script since it just use tool in UE5

you can run project without installing ros2 on your local since ros2 dependency is inside rclUE. you need to make ROS  2 communication work between client/server
